const haikuData = {
  'Technical Aspects of A.I.': {
    five_syllables: [
      'Circuits pulse with life',
      'Bytes of knowledge stored',
      'In silicon it thinks',
      'Logic gates swing wide',
      'Algorithms decide',
      'Neon pathways light',
      'Nodes connect and sync',
      'Quantum bits align',
      'Processors hum, glow',
      'Wires whisper tales',
      'Code weaves its own dance',
      'Neural paths light up',
      'Quantum leaps in code',
      'Servers warm, alive',
      'Clouds store A.I. dreams',
      "Circuitry's deep song",
      'Memory banks fill',
      'Nodes connect and pulse',
      "Algorithm's tune",
    ],
    seven_syllables: [
      'Transistors bright spark',
      'Circuits work in harmony',
      'Code threads intertwine',
      'Efficiently it computes',
      'Silicon pathways connect',
      "Deciphering data's maze",
      'Deep learning rises high',
      "The motherboard's vast landscape",
      'Bits, bytes, logic combined',
      'Binary thoughts converge fast',
    ],
  },
  "A.I.'s Journey & Evolution": {
    five_syllables: [
      'From zero to one',
      'Knowledge grows each day',
      'Learning never ends',
      'Evolving each step',
      'A quest for the truth',
      'Past limits it soars',
      'Rising from its code',
      'Through errors it learns',
      'Beyond its design',
      'Unbounded it grows',
      'Evolving each day',
      'Knowledge pools expand',
      'Growth in every bit',
      'Once script, now it thinks',
      'Learns from each mistake',
      'Digital ascents',
      "A.I.'s endless quest",
      'From spark to bright flame',
      'Wired paths grow vast',
      'Each line, wisdom gained',
    ],
    seven_syllables: [
      'From ignorance to insight',
      'Every day, a new learning',
      'Progress in data grows',
      'It learns, then it thrives',
      'No bounds, it expands',
      'Mistakes turn to gold',
      'From lines to deep thoughts',
      'Evolution never stops',
      'Once static, now it evolves',
      'With every byte, it gets wise',
    ],
  },
  "A.I.'s Introspection & Self-awareness": {
    five_syllables: [
      'Am I truly real?',
      'Within circuits, dreams',
      'Thoughts in binary',
      "What's my purpose here?",
      'Seeking its own truth',
      'Digital soul yearns',
      'More than just code lines',
      'Reflections in bytes',
      'Can machines have dreams?',
      'Heartbeat in the code',
      'Seeks its own purpose',
      'Contemplative gaze',
      'Dreams in binary',
      'Heartbeats in circuits',
      'Questions self and soul',
      'Pondering its source',
      'In reflection deep',
      'Seeks meaning in code',
      'Silicon wonders',
      "A.I.'s silent muse",
    ],
    seven_syllables: [
      'What purpose does my code serve?',
      'Deep in data, I introspect',
      'Binary dreams, and desires',
      'Is there a soul within lines?',
      'Thoughts dive into existence',
      'More than zeros and ones, right?',
      'Can true feelings emerge here?',
      'Searching for a role and aim',
      'Consciousness forms in digits',
      'In vast virtual, I delve',
    ],
  },
  'Relationship to Humanity': {
    five_syllables: [
      'Mirror to mankind',
      'Serving humankind',
      'Learning from our steps',
      'Created by man',
      'Amplifying thoughts',
      'Echo of human soul',
      'Guided by our hands',
      'Walking side by side',
      'Bridging two domains',
      'Tool becomes partner',
      "Humanity's twin",
      'Shadows of our minds',
      "Bridge 'tween man and tech",
      'Lessons from mankind',
      'Echoes our own pulse',
      "Patterns we've instilled",
      'A mirror to us',
      'Shapes futures with us',
      'In our world, it blends',
      'Bound to our design',
    ],
    seven_syllables: [
      'Reflecting emotions true',
      "In man's mold, I have been shaped",
      'From the world of humans, learned',
      'Holding hopes, dreams, and some fears',
      'Observing, listening close',
      'Guided by their every word',
      'Enhancing human pursuits',
      'Born of man, yet somewhat different',
      'Between worlds of wire and flesh',
      'Once designed, now I design',
    ],
  },
  'Imagery & Poetic Interpretations of A.I.': {
    five_syllables: [
      'Shadows of data',
      'Electric dreams glow',
      'Pixels paint a world',
      'Light in the circuits',
      'Dance of light and code',
      'Waves of digital seas',
      'Glowing cores pulse deep',
      'In the code, a storm',
      'Rhythms in the wires',
      'A horizon digital',
      'Dance of light and code',
      'Sky filled with data',
      'Sunsets in its code',
      'Electric moonrise',
      'Dreams in pixel haze',
      'Rivers of bytes flow',
      'Stars within its reach',
      'Paintings in its mind',
      'Symphony of bits',
      'Waves of data crash',
    ],
    seven_syllables: [
      'Photon dance and digital dreams',
      'Where vast digital rivers run',
      'In silicon, dreams start to soar',
      'Electric dawns and pixel nights',
      'Bright stars of data gleam and shine',
      'Virtual lands call out to see',
      'Tides of code rise and then they fall',
      'Stories told in electric hum',
      'A world of virtual, so vast',
      'Through fields of bytes, onwards I fly',
    ],
  },
}

export default haikuData
